### ISSUE TITLE
Sometimes no QA values are received by mros1_reasoner

### ISSUE THREAD

**Issue by chcorbato** [meta-control/mc_mros_reasoner#36]
## Context:
- all metacontrol monitoring input is sent via `/diagnostics` (probably not the best idea I ever had). This input is mainly messages about QA values for energy and safety
- in our system, `/ekf_localization` is also publishing in `/diagnostics`
- a callback in `mros1_reasoner` process these messages to update the KB (runtime ontology in memory)

## Problem
Sometimes no QA values at all are received by `mros1_reasoner`
See **TEST 1** below

This is tricky because it only happens sometimes, especially for `energy` (maybe because they are published less frequently)
See **TEST 2**

I have checked that sometimes energy and safety messages are published **see TEST 3**

Maybe this is related to the messages published in topic `/diagnostics`

Could it be that the diagnostic messages from `/ekf_localization` are "jamming" the topic?

@marioney @gavanderhoorn advice from ROS experts is needed here.

### TEST 1: no QA value messages in `/diagnostics` at all? At least not received by `mros1_reasoner`
**Terminal 1:** simulation + navigation + `rosgraph_monitor`+ `rosgraph_manipulator`
```
roslaunch metacontrol_sim MVP_metacontrol_world.launch
```
**OUTPUT analysis**: All seems to work as expected

**Terminal 2:** `rostopic echo /diagnostics`
```
header: 
  seq: 20
  stamp: 
    secs: 19
    nsecs:  60000000
  frame_id: ''
status: 
  - 
    level: 0
    name: "ekf_localization: Filter diagnostic updater"
    message: "The robot_localization state estimation node appears to be functioning properly."
    hardware_id: "none"
    values: []
  - 
    level: 0
    name: "ekf_localization: odometry/filtered topic status"
    message: ''
    hardware_id: "none"
    values: 
      - 
        key: "Events in window"
        value: "502"
      - 
        key: "Events since startup"
        value: "952"
      - 
        key: "Duration of window (s)"
        value: "10.040000"
      - 
        key: "Actual frequency (Hz)"
        value: "50.000000"
      - 
        key: "Minimum acceptable frequency (Hz)"
        value: "43.200000"
      - 
        key: "Maximum acceptable frequency (Hz)"
        value: "57.200000"
... __AND ONLY MESSAGES LIKE THE ONE ABOVE__

```
**OUTPUT analysis:** All seems to work as expected

**Terminal 3:** `mros1_reasoner`
```
roslaunch mros1_reasoner run.launch onto:=mvp.owl
 ...
RELEVANT OUTPUT
----------------------------
FG Statuses:
fg_standard      None    []
```
**OUTPUT analysis:** The callback for message reception does not seem to be triggered, since there is no output like this:
`[INFO] [1590055021.497386, 38.601000]: received QA observation`

### TEST in which only QA values on `safety` are received
**Terminal 1:** simulation + navigation + `rosgraph_monitor`+ `rosgraph_manipulator`
```
roslaunch metacontrol_sim MVP_metacontrol_world.launch
```
**OUTPUT analysis**: All seems to work as expected

**Terminal 2:** `rostopic echo /diagnostics`
Unfortunately not recorded, trying to reproduce

**Terminal 3:** `mros1_reasoner`
```
roslaunch mros1_reasoner run.launch onto:=mvp.owl
 ...
RELEVANT OUTPUT
----------------------------
[INFO] [1590055014.832565, 36.205000]: received QA observation
received QA about:  mvp.fg_standard     TYPE:  safety
              __5-6 LIKE THE ONE ABOVE on each reasoning period__
...
FG Statuses:
fg_standard      None    [('obs_mvp.safety_10', 1.0), ('obs_mvp.safety_14', 1.0), ('obs_mvp.safety_24', 1.0), ('obs_mvp.safety_33', 1.0), ('obs_mvp.safety_41', 1.0), ('obs_mvp.safety_52', 1.0), ('obs_mvp.safety_61', 1.0)]
```
**OUTPUT analysis:** The callback for message reception is triggered by the received messages with QA safety values

### TEST 3
**Terminal 1:** simulation + navigation + `rosgraph_monitor`+ `rosgraph_manipulator`
```
roslaunch metacontrol_sim MVP_metacontrol_world.launch
```
**OUTPUT analysis**: All seems to work as expected

**Terminal 2:** `rostopic echo /diagnostics`
```
...
---
header: 
  seq: 4
  stamp: 
    secs: 3
    nsecs:         0
  frame_id: ''
status: 
  - 
    level: 0
    name: "ekf_localization: Filter diagnostic updater"
    message: "The robot_localization state estimation node appears to be functioning properly."
    hardware_id: "none"
    values: []
  - 
    level: 0
    name: "ekf_localization: odometry/filtered topic status"
    message: ''
    hardware_id: "none"
    values: 
      - 
        key: "Events in window"
        value: "147"
      - 
        key: "Events since startup"
        value: "147"
      - 
        key: "Duration of window (s)"
        value: "3.000000"
      - 
        key: "Actual frequency (Hz)"
        value: "49.000000"
      - 
        key: "Minimum acceptable frequency (Hz)"
        value: "43.200000"
      - 
        key: "Maximum acceptable frequency (Hz)"
        value: "57.200000"
---
header: 
  seq: 16
  stamp: 
    secs: 2
    nsecs: 802000000
  frame_id: ''
status: 
  - 
    level: 0
    name: ''
    message: "QA status"
    hardware_id: ''
    values: 
      - 
        key: "safety"
        value: "1.0"
---
header: 
  seq: 17
  stamp: 
    secs: 2
    nsecs:   4000000
  frame_id: ''
status: 
  - 
    level: 0
    name: ''
    message: "QA status"
    hardware_id: ''
    values: 
      - 
        key: "energy"
        value: "0.233684937159"

...
```
